### ISSUE TITLE
Pressing plus causes the screen to be covered by a Lightbox effect

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#13]
On the iPhone, pressing the plus button brings up a grey div over the top of the input dialog.

**Comment by drewsdunne** [comment]
Does it? This is odd, this is just a feature with the paper-dialog element, to have the grey background to focus the dialog. I'm not sure how to fix this at the moment but I'll look into it.

**Comment by drewsdunne** [comment]
Just looked at the issues page on GitHub for paper-dialog, there were 28 open issues, and a good amount referring to bugs on the iPhone. I'll try and fix this because our other dialogs seem to be working fine. The issue my arise from the dialog being part of another polymer element and is not top-level like the others. I'll see what I can do when I restructure the apps.

**Comment by andyburnett** [comment]
Seems like it might be a z-order problem.

**Comment by drewsdunne** [comment]
If it is, I'm not doing any z-ordering, I'm not even creating that grey div, I'll have to see if I can modify paper-dialog to do bring the actual dialog out higher.
